export const options = [
    { value: 'all', label: 'all' },
    { value: 'javascript', label: 'javascript' },
    { value: 'python', label: 'python' },
    { value: 'java', label: 'java' },
    { value: 'nodejs', label: 'nodejs' },
    { value: 'reactjs', label: 'reactjs' },
    { value: 'php', label: 'php' },
    { value: 'html', label: 'html' },
    { value: 'css', label: 'css' },
    { value: 'jquery', label: 'jquery' },
    { value: 'mysql', label: 'mysql' },
    { value: 'sql', label: 'sql' },
    { value: 'django', label: 'django' },
    { value: 'angular', label: 'angular' },
    { value: 'ajax', label: 'ajax' },
    { value: 'ruby', label: 'ruby' },
    { value: 'linux', label: 'linux' },
    { value: 'android', label: 'android' },
    { value: 'c#', label: 'c#' },
    { value: 'c', label: 'c' },
    { value: 'c++', label: 'c++' },
    { value: 'laravel', label: 'laravel' },
    { value: 'typescript', label: 'typescript' },
    { value: 'wordpress', label: 'wordpress' },
    { value: 'mongodb', label: 'mongodb' },
    { value: 'windows', label: 'windows' },
    { value: 'postgresql', label: 'postgresql' },
    { value: 'oracle', label: 'oracle' },
    { value: 'git', label: 'git' },
    { value: 'bash', label: 'bash' },
    { value: 'algorithm', label: 'algorithm' },
    { value: 'data structure', label: 'data structure' },
    { value: 'vscode', label: 'vscode' },
    { value: 'docker', label: 'docker' },
    { value: 'firebase', label: 'firebase' },
    { value: 'iphone', label: 'iphone' },
    { value: 'flutter', label: 'flutter' },
    { value: 'powershell', label: 'powershell' },
    
    { value: 'chocolate', label: 'chocolate' },
    { value: 'strawberry', label: 'strawberry' },
    { value: 'vanilla', label: 'vanilla' },
];